name: nas-wot
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cudatoolkit=10.2.89
  - freetype=2.9.1
  - intel-openmp=2020.1
  - jpeg=9b
#  - ld_impl_linux-64=2.33.1
#  - libedit=3.1.20181209
#  - libffi=3.3
#  - libgcc-ng=9.1.0
#  - libgfortran-ng=7.3.0
  - libpng=1.6.37
#  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
#  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.3
  - pillow=7.1.2
  - pip=20.0.2
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytorch=1.5.0
  - pytz=2020.1
#  - readline=8.0
  - setuptools=46.4.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.6.0
  - tqdm=4.46.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - argparse==1.4.0
    - nas-bench-201==1.3
    - tabulate==0.8.7
